version: '2'

services:
  db:
    image: mariadb:10.1
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: pass-root
      MYSQL_USER: user-db
      MYSQL_PASSWORD: pass-user-db
      MYSQL_DATABASE: filerun
    volumes:
      - /home/sysadmin/docker/filerun/db:/var/lib/mysql

  web:
    image: filerun/filerun
    container_name: filerun
    environment:
      FR_DB_HOST: db
      FR_DB_PORT: 3306
      FR_DB_NAME: filerun
      FR_DB_USER: user-db
      FR_DB_PASS: pass-user-db
      APACHE_RUN_USER: www-data
      APACHE_RUN_USER_ID: 33
      APACHE_RUN_GROUP: www-data
      APACHE_RUN_GROUP_ID: 33
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "80:80"
    volumes:
      - /home/sysadmin/docker/filerun/html:/var/www/html
